export const destinationOptions = [
    "Bà Rịa",
    "Bạc Liêu",
    "Bảo Lộc",
    "Bắc Giang",
    "Bắc Kạn",
    "Bắc Ninh",
    "Bến Tre",
    "Biên Hòa",
    "Buôn Ma Thuột",
    "Cà Mau",
    "Cam Ranh",
    "Cao Bằng",
    "Cao Lãnh",
    "Cẩm Phả",
    "Châu Đốc",
    "Chí Linh",
    "Dĩ An",
    "Đà Lạt",
    "Điện Biên Phủ",
    "Đông Hà",
    "Đồng Hới",
    "Đồng Xoài",
    "Gia Nghĩa",
    "Hà Giang",
    "Hạ Long",
    "Hà Tiên",
    "Hà Tĩnh",
    "Hải Dương",
    "Hòa Bình",
    "Hội An",
    "Hồng Ngự",
    "Huế",
    "Hưng Yên",
    "Kon Tum",
    "Lai Châu",
    "Lạng Sơn",
    "Lào Cai",
    "Long Khánh",
    "Long Xuyên",
    "Móng Cái",
    "Mỹ Tho",
    "Nam Định",
    "Ngã Bảy",
    "Nha Trang",
    "Ninh Bình",
    "Phan Rang – Tháp Chàm",
    "Phan Thiết",
    "Phổ Yên",
    "Phủ Lý",
    "Phú Quốc",
    "Phúc Yên",
    "Pleiku",
    "Quảng Ngãi",
    "Quy Nhơn",
    "Rạch Giá",
    "Sa Đéc",
    "Sầm Sơn",
    "Sóc Trăng",
    "Sơn La",
    "Sông Công",
    "Tam Điệp",
    "Tam Kỳ",
    "Tân An",
    "Tân Uyên",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thủ Dầu Một",
    "Thuận An",
    "Trà Vinh",
    "Tuy Hòa",
    "Tuyên Quang",
    "Từ Sơn",
    "Uông Bí",
    "Vị Thanh",
    "Việt Trì",
    "Vinh",
    "Vĩnh Long",
    "Vĩnh Yên",
    "Vũng Tàu",
    "Yên Bái",
];

